// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "OpenMeteoResult.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class OpenMeteoResult
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpCustomModelsGenerator
// App/Edition: App Ext Open Meteo/
// User:        2sic Web-Developer
using System;

namespace AppCode.Extensions.OpenMeteo.Data
{
  // This is a generated custom model class for OpenMeteoResult (scope: Extensions.OpenMeteo)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// OpenMeteoResult custom model. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// This is a lightweight model that inherits from CustomModel. <br/>
  /// For properties, use the strongly-typed access such as `.Json`. <br/>
  /// For advanced features, consider using the full CustomItem instead.
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope Extensions.OpenMeteo.
  /// </remarks>
  public partial class OpenMeteoResult: AutoGenerated.ZAutoGenOpenMeteoResult
  {  }
}

namespace AppCode.Extensions.OpenMeteo.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'OpenMeteoResult' in data scope 'Extensions.OpenMeteo'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenOpenMeteoResult: Custom.Data.CustomModel
  {
    /// <summary>
    /// Json as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Json", scrubHtml: true) etc.
    /// </summary>
    public string Json => _item.String("Json", fallback: "");

    /// <summary>
    /// Latitude as decimal. <br/>
    /// To get other types use methods such as .Int("Latitude")
    /// </summary>
    public decimal Latitude => _item.Decimal("Latitude");

    /// <summary>
    /// Longitude as decimal. <br/>
    /// To get other types use methods such as .Int("Longitude")
    /// </summary>
    public decimal Longitude => _item.Decimal("Longitude");

    /// <summary>
    /// Temperature as decimal. <br/>
    /// To get other types use methods such as .Int("Temperature")
    /// </summary>
    public decimal Temperature => _item.Decimal("Temperature");

    /// <summary>
    /// TimeZone as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TimeZone", scrubHtml: true) etc.
    /// </summary>
    public string TimeZone => _item.String("TimeZone", fallback: "");

    /// <summary>
    /// Weather as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Weather", scrubHtml: true) etc.
    /// </summary>
    public string Weather => _item.String("Weather", fallback: "");

    /// <summary>
    /// WeatherCode as int. <br/>
    /// To get other types use methods such as .Decimal("WeatherCode")
    /// </summary>
    public int WeatherCode => _item.Int("WeatherCode");

    /// <summary>
    /// When as DateTime.
    /// </summary>
    public DateTime When => _item.DateTime("When");

    /// <summary>
    /// WindSpeed as decimal. <br/>
    /// To get other types use methods such as .Int("WindSpeed")
    /// </summary>
    public decimal WindSpeed => _item.Decimal("WindSpeed");
  }
}