// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "DeadPoetSocietyMembership.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class DeadPoetSocietyMembership
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.07.01
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
// When:        2024-05-13 10:32:09Z
namespace AppCode.Data
{
  // This is a generated class for DeadPoetSocietyMembership 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// DeadPoetSocietyMembership data. <br/>
  /// Generated 2024-05-13 10:32:09Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.MembershipNumber`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class DeadPoetSocietyMembership: AutoGenerated.ZAutoGenDeadPoetSocietyMembership
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.DeadPoetSocietyMembership in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenDeadPoetSocietyMembership: Custom.Data.CustomItem
  {
    /// <summary>
    /// MembershipNumber as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MembershipNumber", scrubHtml: true) etc.
    /// </summary>
    public string MembershipNumber => _item.String("MembershipNumber", fallback: "");
  }
}