// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ImgLightbox.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ImgLightbox
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for ImgLightbox 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ImgLightbox data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.ImageLightboxGrouped`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ImgLightbox: AutoGenerated.ZAutoGenImgLightbox
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ImgLightbox in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenImgLightbox: Custom.Data.CustomItem
  {
    /// <summary>
    /// ImageLightboxGrouped as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("ImageLightboxGrouped")
    /// </summary>
    public string ImageLightboxGrouped => _item.Url("ImageLightboxGrouped");

    /// <summary>
    /// Get the file object for ImageLightboxGrouped - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile ImageLightboxGroupedFile => _item.File("ImageLightboxGrouped");

    /// <summary>
    /// Get the folder object for ImageLightboxGrouped.
    /// </summary>

    [JsonIgnore]
    public IFolder ImageLightboxGroupedFolder => _item.Folder("ImageLightboxGrouped");

    /// <summary>
    /// ImageLightboxSolo as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("ImageLightboxSolo")
    /// </summary>
    public string ImageLightboxSolo => _item.Url("ImageLightboxSolo");

    /// <summary>
    /// Get the file object for ImageLightboxSolo - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile ImageLightboxSoloFile => _item.File("ImageLightboxSolo");

    /// <summary>
    /// Get the folder object for ImageLightboxSolo.
    /// </summary>

    [JsonIgnore]
    public IFolder ImageLightboxSoloFolder => _item.Folder("ImageLightboxSolo");

    /// <summary>
    /// ImageNoConfig as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("ImageNoConfig")
    /// </summary>
    public string ImageNoConfig => _item.Url("ImageNoConfig");

    /// <summary>
    /// Get the file object for ImageNoConfig - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile ImageNoConfigFile => _item.File("ImageNoConfig");

    /// <summary>
    /// Get the folder object for ImageNoConfig.
    /// </summary>

    [JsonIgnore]
    public IFolder ImageNoConfigFolder => _item.Folder("ImageNoConfig");

    /// <summary>
    /// LibraryLightboxGallery as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("LibraryLightboxGallery")
    /// </summary>
    public string LibraryLightboxGallery => _item.Url("LibraryLightboxGallery");

    /// <summary>
    /// Get the file object for LibraryLightboxGallery - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LibraryLightboxGalleryFile => _item.File("LibraryLightboxGallery");

    /// <summary>
    /// Get the folder object for LibraryLightboxGallery.
    /// </summary>

    [JsonIgnore]
    public IFolder LibraryLightboxGalleryFolder => _item.Folder("LibraryLightboxGallery");

    /// <summary>
    /// TestId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TestId", scrubHtml: true) etc.
    /// </summary>
    public string TestId => _item.String("TestId", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}