// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "TutorialCategory.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class TutorialCategory
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v18.04.00
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for TutorialCategory 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// TutorialCategory data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Introduction`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class TutorialCategory: AutoGenerated.ZAutoGenTutorialCategory
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.TutorialCategory in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenTutorialCategory: Custom.Data.CustomItem
  {
    /// <summary>
    /// Introduction as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Introduction", scrubHtml: true) etc.
    /// </summary>
    public string Introduction => _item.String("Introduction", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}