// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "TutorialSnippetAddOn.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class TutorialSnippetAddOn
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for TutorialSnippetAddOn 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// TutorialSnippetAddOn data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.AddOnType`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class TutorialSnippetAddOn: AutoGenerated.ZAutoGenTutorialSnippetAddOn
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'TutorialSnippetAddOn' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenTutorialSnippetAddOn: Custom.Data.CustomItem
  {
    /// <summary>
    /// AddOnType as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("AddOnType", scrubHtml: true) etc.
    /// </summary>
    public string AddOnType => _item.String("AddOnType", fallback: "");

    /// <summary>
    /// FilePath as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("FilePath", scrubHtml: true) etc.
    /// </summary>
    public string FilePath => _item.String("FilePath", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// TitleAuto as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TitleAuto", scrubHtml: true) etc.
    /// </summary>
    public string TitleAuto => _item.String("TitleAuto", fallback: "");

    /// <summary>
    /// TitleInternal as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TitleInternal", scrubHtml: true) etc.
    /// </summary>
    public string TitleInternal => _item.String("TitleInternal", fallback: "");
  }
}