// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "UiEmptyHelloWorld.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class UiEmptyHelloWorld
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v18.04.00
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for UiEmptyHelloWorld 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// UiEmptyHelloWorld data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class UiEmptyHelloWorld: AutoGenerated.ZAutoGenUiEmptyHelloWorld
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.UiEmptyHelloWorld in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenUiEmptyHelloWorld: Custom.Data.CustomItem
  {  }
}