// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "UiPickerIconsSvgFromApp.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class UiPickerIconsSvgFromApp
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for UiPickerIconsSvgFromApp 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// UiPickerIconsSvgFromApp data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.IconsCheckboxes`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class UiPickerIconsSvgFromApp: AutoGenerated.ZAutoGenUiPickerIconsSvgFromApp
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.UiPickerIconsSvgFromApp in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenUiPickerIconsSvgFromApp: Custom.Data.CustomItem
  {
    /// <summary>
    /// IconsCheckboxes as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("IconsCheckboxes", scrubHtml: true) etc.
    /// </summary>
    public string IconsCheckboxes => _item.String("IconsCheckboxes", fallback: "");

    /// <summary>
    /// IconsDropdown as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("IconsDropdown", scrubHtml: true) etc.
    /// </summary>
    public string IconsDropdown => _item.String("IconsDropdown", fallback: "");

    /// <summary>
    /// IconsRadio as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("IconsRadio", scrubHtml: true) etc.
    /// </summary>
    public string IconsRadio => _item.String("IconsRadio", fallback: "");
  }
}