// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "UiPickerIconsMaterial.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class UiPickerIconsMaterial
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for UiPickerIconsMaterial 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// UiPickerIconsMaterial data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.IconDropdown`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class UiPickerIconsMaterial: AutoGenerated.ZAutoGenUiPickerIconsMaterial
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.UiPickerIconsMaterial in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenUiPickerIconsMaterial: Custom.Data.CustomItem
  {
    /// <summary>
    /// IconDropdown as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("IconDropdown", scrubHtml: true) etc.
    /// </summary>
    public string IconDropdown => _item.String("IconDropdown", fallback: "");

    /// <summary>
    /// IconRadio as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("IconRadio", scrubHtml: true) etc.
    /// </summary>
    public string IconRadio => _item.String("IconRadio", fallback: "");

    /// <summary>
    /// IconsCheckboxes as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("IconsCheckboxes", scrubHtml: true) etc.
    /// </summary>
    public string IconsCheckboxes => _item.String("IconsCheckboxes", fallback: "");
  }
}