// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "UiPickerImagesFromApp.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class UiPickerImagesFromApp
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for UiPickerImagesFromApp 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// UiPickerImagesFromApp data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Checkboxes`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class UiPickerImagesFromApp: AutoGenerated.ZAutoGenUiPickerImagesFromApp
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.UiPickerImagesFromApp in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenUiPickerImagesFromApp: Custom.Data.CustomItem
  {
    /// <summary>
    /// Checkboxes as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Checkboxes", scrubHtml: true) etc.
    /// </summary>
    public string Checkboxes => _item.String("Checkboxes", fallback: "");

    /// <summary>
    /// Dropdown as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Dropdown", scrubHtml: true) etc.
    /// </summary>
    public string Dropdown => _item.String("Dropdown", fallback: "");

    /// <summary>
    /// Radio as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Radio", scrubHtml: true) etc.
    /// </summary>
    public string Radio => _item.String("Radio", fallback: "");
  }
}