// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "UiStringColorPickr.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class UiStringColorPickr
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.08.00
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
// When:        2024-05-21 19:46:38Z
namespace AppCode.Data
{
  // This is a generated class for UiStringColorPickr 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// UiStringColorPickr data. <br/>
  /// Generated 2024-05-21 19:46:38Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Color1`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class UiStringColorPickr: AutoGenerated.ZAutoGenUiStringColorPickr
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.UiStringColorPickr in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenUiStringColorPickr: Custom.Data.CustomItem
  {
    /// <summary>
    /// Color1 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Color1", scrubHtml: true) etc.
    /// </summary>
    public string Color1 => _item.String("Color1", fallback: "");

    /// <summary>
    /// Color2 as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Color2", scrubHtml: true) etc.
    /// </summary>
    public string Color2 => _item.String("Color2", fallback: "");

    /// <summary>
    /// ColorWithDefault as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ColorWithDefault", scrubHtml: true) etc.
    /// </summary>
    public string ColorWithDefault => _item.String("ColorWithDefault", fallback: "");
  }
}