// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "UiStringColorPickerSpectrumPro.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class UiStringColorPickerSpectrumPro
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for UiStringColorPickerSpectrumPro 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// UiStringColorPickerSpectrumPro data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Color`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class UiStringColorPickerSpectrumPro: AutoGenerated.ZAutoGenUiStringColorPickerSpectrumPro
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.UiStringColorPickerSpectrumPro in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenUiStringColorPickerSpectrumPro: Custom.Data.CustomItem
  {
    /// <summary>
    /// Color as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Color", scrubHtml: true) etc.
    /// </summary>
    public string Color => _item.String("Color", fallback: "");
  }
}