// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "UiStringColorPickrPro.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class UiStringColorPickrPro
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.00
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
// When:        2024-03-28 18:17:21Z
namespace AppCode.Data
{
  // This is a generated class for UiStringColorPickrPro 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// UiStringColorPickrPro data. <br/>
  /// Generated 2024-03-28 18:17:21Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.PickerWith2sicPresets`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class UiStringColorPickrPro: AutoGenerated.ZagUiStringColorPickrPro
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.UiStringColorPickrPro in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagUiStringColorPickrPro: Custom.Data.CustomItem
  {
    /// <summary>
    /// PickerWith2sicPresets as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("PickerWith2sicPresets", scrubHtml: true) etc.
    /// </summary>
    public string PickerWith2sicPresets => _item.String("PickerWith2sicPresets", fallback: "");

    /// <summary>
    /// PickerWithNoPresets as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("PickerWithNoPresets", scrubHtml: true) etc.
    /// </summary>
    public string PickerWithNoPresets => _item.String("PickerWithNoPresets", fallback: "");
  }
}