// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ZzzTemp.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ZzzTemp
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.07.01
// App/Edition: Tutorial-Razor/
// User:        2sic Web-Developer
// When:        2024-05-13 10:32:09Z
using System.Collections.Generic;
using ToSic.Sxc.Data;

namespace AppCode.Data
{
  // This is a generated class for ZzzTemp 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ZzzTemp data. <br/>
  /// Generated 2024-05-13 10:32:09Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.PickerFieldTree`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ZzzTemp: AutoGenerated.ZAutoGenZzzTemp
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ZzzTemp in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenZzzTemp: Custom.Data.CustomItem
  {
    /// <summary>
    /// PickerFieldTree as single item of ITypedItem.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. 
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public ITypedItem PickerFieldTree => _pickerFieldTree ??= _item.Child("PickerFieldTree");
    private ITypedItem _pickerFieldTree;
  }
}